enums:
  UserStatus:
    INACTIVE: 0
    ACTIVE: 1
    REMOVED: 2

classes:
  User:
    properties:
      name: string
      registrationDate:
        type: date
        nullable: true
      status:
        type: UserStatus
        default: INACTIVE
      addresses: collection<Address>

  Address:
      properties:
        street: string
        city: string
